---
title: "Day3_ShapExplanation"
format: html
---

```{r setup, include=FALSE, message=TRUE, warning=TRUE}

# Set options
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.width = 12, 
                      fig.height =  8,
                      include = TRUE,
                      echo = TRUE)

# Load the necessary packages
library(tidyverse)
library(dplyr)
library(here)
library(caret)
```


```{r read_data, message=FALSE, warning=FALSE}
churn <- read_csv(here('data/raw', 'Churn_Modelling.csv'))
head(churn)
```
## Data Partition for training and prediction.
```{r}
set.seed(123)

churn <- churn %>%
  mutate(Exited = factor(Exited))   # 0 = stayed, 1 = churned

train_index <- createDataPartition(churn$Exited, p = 0.8, list = FALSE)

train <- churn[train_index, ]
test  <- churn[-train_index, ]
```

## RG model with class weight to counter the imbalance 
```{r}
library(ranger)
class_weights <- c("0" = 1, "1" = 4)   # churners 4x weight
set.seed(123)

rf_w_model <- ranger(
  Exited ~ Geography + Gender + Age + Tenure +
    NumOfProducts + IsActiveMember + CreditScore + Balance,
  data       = train,
  ntree      = 300,    # number of trees
  mtry       = 3,      # no. of variables tried at each split (sqrt of 8 ≈ 3)
  probability    = TRUE,
  class.weights  = class_weights
)

print(rf_w_model)
```

```{r}
rf_w_probs <- predict(rf_w_model, data = test)$predictions[, "1"]

rf_w_pred_03 <- ifelse(rf_w_probs >= 0.3, "1", "0")
rf_w_pred_03 <- factor(rf_w_pred_03, levels = c("0", "1"))

rf_w_cm_03 <- confusionMatrix(rf_w_pred_03, test$Exited, positive = "1")
rf_w_cm_03
rf_w_cm_03$byClass[c("Recall", "Precision")]
```
# 4. Compute SHAP values
shap_vals <- treeshap(unified, X_explain)

# 5. Global importance / beeswarm
plot_importance(shap_vals)            # bar plot: top global drivers
plot_shap_summary(shap_vals)          # beeswarm-style summary if available

